# Generated by Django 2.2.17 on 2021-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_room', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
