# Generated by Django 2.2.17 on 2021-01-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_room', '0003_auto_20210130_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room', 'date')},
        ),
    ]
